name: Build apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build all apps
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build apps
        uses: home-assistant/builder@master
        with:
          args: |
            --all
            --amd64
            --aarch64
            --test
